# Generated by Django 5.0.6 on 2024-07-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(default='Black', max_length=255),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default='M', max_length=255),
        ),
    ]
