# Generated by Django 5.0.6 on 2024-07-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_cart_color_cart_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='color',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(max_length=255),
        ),
    ]
