# Generated by Django 5.0.6 on 2024-07-28 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_order_item_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='order_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
