# Generated by Django 5.0.6 on 2024-07-29 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_alter_order_item_cart'),
        ('Products', '0017_review_id_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.product'),
            preserve_default=False,
        ),
    ]
