# Generated by Django 5.0.6 on 2024-07-29 12:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_order_item_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='product',
        ),
        migrations.AddField(
            model_name='order_item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_item',
            name='product_price',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='order_number',
            field=models.IntegerField(unique=True),
        ),
    ]
