# Generated by Django 5.0.6 on 2024-07-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_remove_order_item_product_order_item_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
