# Generated by Django 5.0.6 on 2024-07-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_order_item_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='order_number',
            field=models.IntegerField(),
        ),
    ]
