# Generated by Django 5.0.6 on 2024-07-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_alter_order_item_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='sub_total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_item',
            name='tax',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
