# Generated by Django 5.0.6 on 2024-07-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_alter_product_color_alter_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Grey', 'Grey')], max_length=255, null=True),
        ),
    ]
