# Generated by Django 5.0.6 on 2024-07-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('Medium', 'Medium'), ('L', 'L'), ('XL', 'XL')], max_length=255, null=True),
        ),
    ]
