# Generated by Django 5.0.6 on 2024-08-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0018_review_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('TShirt', 'TShirt'), ('Jeans', 'Jeans'), ('Jacket', 'Jacket'), ('Sweater', 'Sweater'), ('Shorts', 'Shorts'), ('Socks', 'Socks'), ('Shoes', 'Shoes'), ('Parse', 'Parse'), ('Heals', 'Heals')], max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_rating',
            field=models.FloatField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
